### PR TITLE
adjust netty version requirement

### PR DESCRIPTION
**Pull request by chrislusf**
This use basic netty feature so that tChannel can work with Spark.

### CODE REVIEW

**Comment by junchaowu** [comment]
this is not going to work.

**Comment by breerly** [comment]
Mind elaborating?

**Comment by chrislusf** [comment]
not ready yet.

**Comment by breerly** [comment]
Please remove the `WIP -` prefix from this PR when it's ready to review.

**Comment by junchaowu** [comment]
We are not going to do this approach because we should change Netty's version because of Spark. It could happen again on some day when there is another library using other version's Netty, asking to change version.

**Pull request closed without merging**
