### PR TITLE
Manual fix of maven release plugin error

### PR DESCRIPTION
**Pull request by jamestzchang**
Tried using defaults for the release process, something went wrong - will do a dry run next time - here's the manual fix to revert back to what it used t obe

### CODE REVIEW

**Comment by blampe** [comment]
@junchaowu @abhinav

**Comment by breerly** [comment]
Is this a regular part of the release process?

**Comment by junchaowu** [comment]
the regular release process will automatically help you release that.

**Comment by jamestzchang** [comment]
I kept getting errors in the release process and from what I can tell a
manual revert needs to be done.  The release errored at the end, then when
I tried to rerun, it errored midway from the git logs it looks like it
didn't complete creating a developer snapshot version - this checkin
creates the developer snapshot version

**Pull request merged**
